from .grid_nodes import NODE_CLASS_MAPPINGS as GRID_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GRID_NAMES
from .render_nodes import NODE_CLASS_MAPPINGS as RENDER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RENDER_NAMES

NODE_CLASS_MAPPINGS = {**GRID_MAPPINGS, **RENDER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**GRID_NAMES, **RENDER_NAMES}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
